import { MembershipTier, FeatureItem, TierFeature, UsagePeriod } from '../types';

export const DEFAULT_MEMBERSHIP_TIERS: MembershipTier[] = [
  {
    id: 'free',
    name: '무료 회원',
    description: '기본 가입 회원 무료 체험 혜택 (일일 제한 제공)',
    isActive: true,
    sortOrder: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'basic',
    name: '베이직',
    description: '네이버 블로그 초보자를 위한 실속형 입문 플랜',
    isActive: true,
    sortOrder: 2,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'pro',
    name: 'PRO',
    description: '블로그 수익화 최적화 및 프리미엄 AI 패키지',
    isActive: true,
    sortOrder: 3,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'vip',
    name: 'VIP 마스터',
    description: '상위 1% 전문 블로거 및 대량 포스팅 무제한 이용권',
    isActive: true,
    sortOrder: 4,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'admin',
    name: '관리자',
    description: '시스템 최고 관리자 (모든 기능 및 관리 권한 포함)',
    isActive: true,
    sortOrder: 99,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const DEFAULT_FEATURES: FeatureItem[] = [
  {
    id: 'feat_seo_plan',
    featureKey: 'seo_plan',
    name: 'SEO 콘텐츠 기획안 생성',
    description: '실시간 네이버 검색 상위 노출 최적화 5종 키워드 조합 및 H2 소제목 설계',
    category: 'ai_draft',
    isActive: true,
    sortOrder: 1,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_ai_draft',
    featureKey: 'ai_draft',
    name: 'AI 본문 초안 생성',
    description: '5대 글 작성 스타일(경험리뷰/정보탐색/구매추천/비교/홈판) 맞춤형 블로그 본문 완성',
    category: 'ai_draft',
    isActive: true,
    sortOrder: 2,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_multi_keyword_draft',
    featureKey: 'multi_keyword_draft',
    name: '다중 키워드 일괄 초안 생성',
    description: '트렌드 키워드 다중 선택 후 1회 클릭으로 순차 일괄 큐 생성',
    category: 'ai_draft',
    isActive: true,
    sortOrder: 3,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_image_search',
    featureKey: 'image_search',
    name: '무료 상업용 이미지 검색',
    description: 'Unsplash 기반 본문 소제목 연관 고화질 무료 이미지 원클릭 매칭',
    category: 'ai_draft',
    isActive: true,
    sortOrder: 4,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_card_news',
    featureKey: 'card_news',
    name: '카드뉴스 자동 제작 스튜디오',
    description: '본문 핵심 내용 기반 인스타그램/블로그 썸네일 카드뉴스 슬라이드 생성',
    category: 'ai_draft',
    isActive: true,
    sortOrder: 5,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_trend_keyword',
    featureKey: 'trend_keyword',
    name: '황금 트렌드 키워드 분석',
    description: '네이버 데이터랩 및 검색광고 기반 급상승/포스팅 활용형 키워드 발굴',
    category: 'analytics',
    isActive: true,
    sortOrder: 6,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_blog_analysis',
    featureKey: 'blog_analysis',
    name: '블로그 문체 분석 및 벤치마킹',
    description: '내 블로그 기존 포스팅의 문체, 문단 길이, 종결어미 패턴 심층 분석',
    category: 'analytics',
    isActive: true,
    sortOrder: 7,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_challenge',
    featureKey: 'challenge',
    name: '챌린지 참여 및 일일 인증',
    description: '진행 중인 기수별 챌린지 신청, 자동 포스팅 집계 및 스트릭 달성',
    category: 'challenge',
    isActive: true,
    sortOrder: 8,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_challenge_admin',
    featureKey: 'challenge_admin',
    name: '챌린지 개설 및 관리자 권한',
    description: '챌린지 그룹 생성, 참가자 관리, 입금 승인 및 환급 계산',
    category: 'challenge',
    isActive: true,
    sortOrder: 9,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'feat_hall_of_fame',
    featureKey: 'hall_of_fame',
    name: '수익 인증 및 명예의 전당',
    description: '블로그 제휴 마케팅 / 애드포스트 수익 인증 등록 및 명예의 전당 등재',
    category: 'revenue',
    isActive: true,
    sortOrder: 10,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
];

export const FEATURE_CATEGORIES = [
  { id: 'ai_draft', name: 'AI 초안 생성기', description: 'SEO 기획안, 본문 초안, 카드뉴스 등 AI 콘텐츠 생성 도구' },
  { id: 'analytics', name: '블로그 분석 & 키워드', description: '트렌드 키워드, 상위 문서 벤치마킹, 문체 분석 도구' },
  { id: 'challenge', name: '챌린지', description: '챌린지 참가, 스트릭 집계, 환급 및 관리 기능' },
  { id: 'revenue', name: '수익 인증 & 뱃지', description: '수익 인증 게시판, 명예의 전당, 성과 뱃지 시스템' },
];

export const DEFAULT_TIER_FEATURES: Record<string, Record<string, { enabled: boolean; usageLimit: number | null; usagePeriod: UsagePeriod }>> = {
  free: {
    seo_plan: { enabled: true, usageLimit: 3, usagePeriod: 'daily' },
    ai_draft: { enabled: true, usageLimit: 3, usagePeriod: 'daily' },
    multi_keyword_draft: { enabled: false, usageLimit: 0, usagePeriod: 'monthly' },
    image_search: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    card_news: { enabled: false, usageLimit: 0, usagePeriod: 'monthly' },
    trend_keyword: { enabled: true, usageLimit: 20, usagePeriod: 'daily' },
    blog_analysis: { enabled: true, usageLimit: 1, usagePeriod: 'daily' },
    challenge: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    challenge_admin: { enabled: false, usageLimit: 0, usagePeriod: 'none' },
    hall_of_fame: { enabled: true, usageLimit: null, usagePeriod: 'none' },
  },
  basic: {
    seo_plan: { enabled: true, usageLimit: 30, usagePeriod: 'monthly' },
    ai_draft: { enabled: true, usageLimit: 20, usagePeriod: 'monthly' },
    multi_keyword_draft: { enabled: true, usageLimit: 10, usagePeriod: 'monthly' },
    image_search: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    card_news: { enabled: true, usageLimit: 10, usagePeriod: 'monthly' },
    trend_keyword: { enabled: true, usageLimit: 100, usagePeriod: 'daily' },
    blog_analysis: { enabled: true, usageLimit: 10, usagePeriod: 'monthly' },
    challenge: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    challenge_admin: { enabled: false, usageLimit: 0, usagePeriod: 'none' },
    hall_of_fame: { enabled: true, usageLimit: null, usagePeriod: 'none' },
  },
  pro: {
    seo_plan: { enabled: true, usageLimit: 100, usagePeriod: 'monthly' },
    ai_draft: { enabled: true, usageLimit: 60, usagePeriod: 'monthly' },
    multi_keyword_draft: { enabled: true, usageLimit: 30, usagePeriod: 'monthly' },
    image_search: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    card_news: { enabled: true, usageLimit: 30, usagePeriod: 'monthly' },
    trend_keyword: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    blog_analysis: { enabled: true, usageLimit: 30, usagePeriod: 'monthly' },
    challenge: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    challenge_admin: { enabled: false, usageLimit: 0, usagePeriod: 'none' },
    hall_of_fame: { enabled: true, usageLimit: null, usagePeriod: 'none' },
  },
  vip: {
    seo_plan: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    ai_draft: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    multi_keyword_draft: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    image_search: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    card_news: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    trend_keyword: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    blog_analysis: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    challenge: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    challenge_admin: { enabled: false, usageLimit: 0, usagePeriod: 'none' },
    hall_of_fame: { enabled: true, usageLimit: null, usagePeriod: 'none' },
  },
  admin: {
    seo_plan: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    ai_draft: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    multi_keyword_draft: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    image_search: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    card_news: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    trend_keyword: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    blog_analysis: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    challenge: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    challenge_admin: { enabled: true, usageLimit: null, usagePeriod: 'none' },
    hall_of_fame: { enabled: true, usageLimit: null, usagePeriod: 'none' },
  },
};

export const DEFAULT_PRODUCTS: import('../types').Product[] = [
  {
    id: 'prod_basic_1m',
    name: '베이직 멤버십 (30일)',
    description: '블로그 초보자를 위한 월 30회 AI 초안 & 트렌드 키워드 분석권',
    productType: 'membership',
    price: 19000,
    originalPrice: 29000,
    membershipTier: 'basic',
    durationDays: 30,
    isActive: true,
    sortOrder: 1,
    badge: '실속형',
    features: ['AI 초안 월 20회 생성', 'SEO 기획안 월 30회', '트렌드 키워드 일 100회', '카드뉴스 월 10회'],
  },
  {
    id: 'prod_pro_1m',
    name: 'PRO 멤버십 (30일)',
    description: '블로그 수익화 최적화 패키지 (챌린지 참가자 기본 혜택)',
    productType: 'membership',
    price: 39000,
    originalPrice: 59000,
    membershipTier: 'pro',
    durationDays: 30,
    isActive: true,
    sortOrder: 2,
    badge: 'BEST',
    features: ['AI 초안 월 60회 생성', '다중 키워드 일괄 생성 30회', '황금 키워드 무제한 검색', '카드뉴스 30회'],
  },
  {
    id: 'prod_pro_3m',
    name: 'PRO 멤버십 (90일 패키지)',
    description: '3개월 집중 수익화 챌린지 및 마케팅 블로거 추천',
    productType: 'membership',
    price: 99000,
    originalPrice: 177000,
    membershipTier: 'pro',
    durationDays: 90,
    isActive: true,
    sortOrder: 3,
    badge: '44% 할인',
    features: ['PRO 3개월 연속 이용권', 'AI 초안 매월 60회', '모든 기능 우선 지원'],
  },
  {
    id: 'prod_vip_1m',
    name: 'VIP 마스터 무제한 (30일)',
    description: '상위 1% 전문 블로거 및 마케팅 대행사를 위한 모든 AI 무제한 플랜',
    productType: 'membership',
    price: 89000,
    originalPrice: 129000,
    membershipTier: 'vip',
    durationDays: 30,
    isActive: true,
    sortOrder: 4,
    badge: '무제한',
    features: ['AI 초안 무제한 생성', 'SEO 기획안 무제한', '카드뉴스 무제한 제작', '문체 분석 무제한'],
  },
];

